name: Build CLX S20P
on:
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 360
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt update -y
          sudo apt install -y build-essential cmake flex git libssl-dev libncurses-dev g++ gcc-multilib gawk gettext libelf-dev python3 quilt subversion unzip zlib1g-dev ccache libtool-bin

      - name: Clone source code
        run: git clone https://github.com/chasey-dev/immortalwrt-mt798x-rebase.git openwrt

      - name: Copy .config to source
        run: cp -f .config openwrt/.config

      - name: Update feeds
        run: |
          cd openwrt
          ./scripts/feeds clean
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Generate config
        run: |
          cd openwrt
          make defconfig

      - name: Download packages
        run: |
          cd openwrt
          make download -j10

      - name: Build firmware
        run: |
          cd openwrt
          make -j1 V=s

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: clx-s20p-firmware
          path: openwrt/bin/targets/mediatek/filogic/*.bin
